/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Presentation from "../components/Presentation";
import Services from "../components/Services";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState, useRef } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const aboutRef = useRef(null);
  const projectsRef = useRef(null);
  const contactRef = useRef(null);
  const skillsRef = useRef(null);

  const scrollToAbout = () => {
    aboutRef.current.scrollIntoView({ behavior: "smooth" });
  }

  const scrollToProjects = () => {
    projectsRef.current.scrollIntoView({ behavior: "smooth" });
  }

  const scrollToContact = () => {
    contactRef.current.scrollIntoView({ behavior: "smooth" });
  }

  const scrollToSkills = () => {
    skillsRef.current.scrollIntoView({ behavior: "smooth" });
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>GPCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
          <nav className="py-6 mb-4 flex justify-between dark:text-white sticky top-0 z-50 backdrop-blur-lg">
            <h1 className="font-burtons text-xl font-semibold">GPCH</h1>
            <ul className="flex items-center gap-2 lg:gap-10">
              <li><button onClick={scrollToAbout}>About</button></li>
              <li><button onClick={scrollToSkills}>Skills</button></li>
              <li><button onClick={scrollToProjects}>Projects</button></li>
              <li><button onClick={scrollToContact}>Contact</button></li>
            </ul>
            <BsFillMoonStarsFill
              onClick={() => setDarkMode(!darkMode)}
              className=" cursor-pointer text-xl"
            />
          </nav>
        <section ref={aboutRef} className="pb-20 pt-10">
          <Presentation/>
        </section>

        <section className="py-20" ref={skillsRef}>
          <Services />
        </section>

        <section className="py-20" ref={projectsRef}>
          <Projects />
        </section>
        <section ref={contactRef}>
          <Contact />
        </section>
      </main>
    </div>
  );
}
